### ISSUE TITLE
Can this work for Godot 4+ games with multiplayer and open world chunks?

### ISSUE THREAD

**Issue by WithinAmnesia** [DarkShadowNemo/Godot-GSC-Chunk-Importer#1]
Test chunks link: https://github.com/WithinAmnesia/ARPG/discussions/15

I'm trying to find a way to seamless load and unload chunks for a 2D multiplayer game project to make an open world with a working server using Godot 4.2.1.NET.

How can this work for multiplayer and what is needed for this to potentially work? What options can be used for chunk loading and unloading seamlessly in Godot 4.2.1.NET? Please give feedback.

**Comment by DarkShadowNemo** [comment]
it will never work on 2d multiplayer game project or 2d stuff, this only works on 3d stuff only, this file format is only used for travellers tales file format that uses the same format like nemo, twoc, haven, lsw1 and weakest link the format hasn't been cracked yet on the gsc but in godot 4x, it will only work on small gsc levels except mask chase and a few which that is godot 4x fault for crashing randomly when opening a new scene to it, see the 3d offset here it will only work on 3d games only that uses the same format, i'm closing this, this is not related for 2d stuff 
![gsc offfset](https://github.com/DarkShadowNemo/Godot-GSC-Chunk-Importer/assets/119450522/c80cf3ed-dc3f-453d-acdb-d45bcf66180b)

**Comment by WithinAmnesia** [comment]
Here is an update since I last posted.
https://jonathaneeckhout.itch.io/jdungeon For the goal right now it is easy to play this but imagine it has seamless chunk loading and unloading. As instead of the black world boundary a new chunk loads in seamlessly. What are your suggestions and thoughts?

Update: https://github.com/WithinAmnesia/ARPG/tree/ARPG-Infinite-Worlds Here is the 128x128 with 32x32 pixel tile chunk to test.

My initial testing seems to feel even faster combat with the 128x128 chunk. This 128x128 chunk has the same amount of entities as the 256x256 chunk. For I moved all of the entities over into the 128x128 chunk. This 128x128 chunk is a good test for using the Infinite-Worlds using the BinarySerializer for Godot 4.2+ from Theraot: https://gist.github.com/theraot/31515e28e2d8bfea33f6c6d5bcd852f6 . There needs to be some testing how to make the chunks seamlessly load and unload. https://gamedev.stackexchange.com/questions/209002/looking-for-help-godot-4-multiplayer-seamless-open-world-chunks

**Comment by WithinAmnesia** [comment]
> it will never work on 2d multiplayer game project or 2d stuff, this only works on 3d stuff only, this file format is only used for travellers tales file format that uses the same format like nemo, twoc, haven, lsw1 and weakest link the format hasn't been cracked yet on the gsc but in godot 4x, it will only work on small gsc levels except mask chase and a few which that is godot 4x fault for crashing randomly when opening a new scene to it, see the 3d offset here it will only work on 3d games only that uses the same format, i'm closing this, this is not related for 2d stuff ![gsc offfset](https://private-user-images.githubusercontent.com/119450522/305647772-c80cf3ed-dc3f-453d-acdb-d45bcf66180b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxODgyNjcsIm5iZiI6MTcwODE4Nzk2NywicGF0aCI6Ii8xMTk0NTA1MjIvMzA1NjQ3NzcyLWM4MGNmM2VkLWRjM2YtNDUzZC1hY2RiLWQ0NWJjZjY2MTgwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxNjM5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDUwN2FlYWIzYzNiNDJlYjcyMmExZGJmN2YxOGYwMjRmOWI2ZjBiZGNiZTlhYzUzNzg3ZDZkZDEwZTBmNGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.orH9Ljm2MDm8i-dj7Esvi7Iib_OEPZ1V2ppNKSBnHDY)



> it will never work on 2d multiplayer game project or 2d stuff, this only works on 3d stuff only, this file format is only used for travellers tales file format that uses the same format like nemo, twoc, haven, lsw1 and weakest link the format hasn't been cracked yet on the gsc but in godot 4x, it will only work on small gsc levels except mask chase and a few which that is godot 4x fault for crashing randomly when opening a new scene to it, see the 3d offset here it will only work on 3d games only that uses the same format, i'm closing this, this is not related for 2d stuff ![gsc offfset](https://private-user-images.githubusercontent.com/119450522/305647772-c80cf3ed-dc3f-453d-acdb-d45bcf66180b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxODgyNjcsIm5iZiI6MTcwODE4Nzk2NywicGF0aCI6Ii8xMTk0NTA1MjIvMzA1NjQ3NzcyLWM4MGNmM2VkLWRjM2YtNDUzZC1hY2RiLWQ0NWJjZjY2MTgwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxNjM5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDUwN2FlYWIzYzNiNDJlYjcyMmExZGJmN2YxOGYwMjRmOWI2ZjBiZGNiZTlhYzUzNzg3ZDZkZDEwZTBmNGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.orH9Ljm2MDm8i-dj7Esvi7Iib_OEPZ1V2ppNKSBnHDY)

Can you take a look at the test chunk? https://github.com/WithinAmnesia/ARPG/tree/ARPG-Infinite-Worlds Here is the 128x128 with 32x32 pixel tile chunk to test.

Also any help with what to do next to solve multiplayer chunk seamless loading and unloading is really important right now for the entire community will win once its solved. You seem to be really skilled and like what would you suggestion be done to find solutions for implementing multiplayer seamless chunk loading and unloading? Also what are your thoughts on Theraot's code and what also should be done for possible solutions to solve this community wide puzzle?

Please if you feel interested testing the chunk is really helpful. If you are interested and also if you are curious take a look at theraot's code and may you can find new ideas to implement these things together or another way to make things work well. I really hope to find solutions and this will probably take an open minded community to solve. It is really important to get any ideas and questions and suggestions on what to do now too. Please feel free and tinker around and like any feedback is welcome.
